name: Auto-build Cap Desktop Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., cap-v1.2.3)'
        required: false
        type: string
  workflow_call:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag: ${{ steps.get-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get version info
        id: get-version
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            TAG="${{ inputs.tag }}"
          else
            # Get the latest cap-v* tag
            TAG=$(git tag -l "cap-v*" --sort=-version:refname | head -n1)
          fi
          
          if [ -z "$TAG" ]; then
            echo "No tag found"
            exit 1
          fi
          
          VERSION=${TAG#cap-v}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION (tag: $TAG)"

  build:
    needs: get-version
    strategy:
      fail-fast: false
      matrix:
        settings:
          - target: x86_64-apple-darwin
            runner: macos-latest
            name: "macOS Intel"
          - target: aarch64-apple-darwin
            runner: macos-latest
            name: "macOS Apple Silicon"
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            name: "Windows x64"
    
    runs-on: ${{ matrix.settings.runner }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Fetch upstream tags and checkout
        run: |
          git remote add upstream https://github.com/CapSoftware/Cap.git || true
          git fetch upstream --tags
          git checkout ${{ needs.get-version.outputs.tag }}
        shell: bash
          
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}
          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.settings.target }}
          
      - uses: ./.github/actions/setup-js

      - name: Create API Key File (macOS)
        if: matrix.settings.runner == 'macos-latest'
        run: echo "${{ secrets.APPLE_API_KEY_FILE }}" > api.p8

      - name: Import Apple certificates (macOS)
        if: matrix.settings.runner == 'macos-latest'
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Verify certificate (macOS)
        if: matrix.settings.runner == 'macos-latest'
        run: security find-identity -v -p codesigning ${{ runner.temp }}/build.keychain
      
      - name: Create .env file
        run: |
          echo "appVersion=${{ needs.get-version.outputs.version }}" >> .env
          echo "VITE_ENVIRONMENT=production" >> .env
          echo "VITE_SERVER_URL=https://cap.so" >> .env
          echo "NEXT_PUBLIC_WEB_URL=https://cap.so" >> .env
          echo "NEXTAUTH_URL=https://cap.so" >> .env
          echo "NEXT_PUBLIC_CAP_AWS_REGION=us-east-1" >> .env
          echo "NEXT_PUBLIC_CAP_AWS_BUCKET=cap-so-public" >> .env
          echo "RUST_TARGET_TRIPLE=${{ matrix.settings.target }}" >> .env
        shell: bash
          
      - name: Copy .env to desktop app
        run: cp .env apps/desktop/.env
        shell: bash
        
      - name: Build app
        working-directory: apps/desktop
        run: |
          pnpm -w cap-setup
          pnpm build:tauri --target ${{ matrix.settings.target }} --config src-tauri/tauri.opensource.conf.json
        env:
          # https://github.com/tauri-apps/tauri-action/issues/740
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_TARGET_TRIPLE: ${{ matrix.settings.target }}
          TAURI_ENV_TARGET_TRIPLE: ${{ matrix.settings.target }}
          TAURI_SIGNING_PRIVATE_KEY: ""
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""
          # Apple codesigning (macOS only)
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          # Apple notarization (macOS only)
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_PATH: ${{ github.workspace }}/api.p8
          APPLE_KEYCHAIN: ${{ runner.temp }}/build.keychain
          
      - name: Prepare artifacts (macOS)
        if: matrix.settings.runner == 'macos-latest'
        run: |
          mkdir -p artifacts
          cd target/${{ matrix.settings.target }}/release
          
          # Copy the CLI binary if it exists
          if [ -f "cap" ]; then
            cp cap "$GITHUB_WORKSPACE/artifacts/cap-${{ matrix.settings.target }}"
            chmod +x "$GITHUB_WORKSPACE/artifacts/cap-${{ matrix.settings.target }}"
          fi
          if [ -f "Cap" ]; then
            cp Cap "$GITHUB_WORKSPACE/artifacts/cap-${{ matrix.settings.target }}"
            chmod +x "$GITHUB_WORKSPACE/artifacts/cap-${{ matrix.settings.target }}"
          fi
          
          # Copy .app bundle if it exists
          if [ -d "bundle/macos" ]; then
            find bundle/macos -name "*.app" -exec cp -r {} "$GITHUB_WORKSPACE/artifacts/" \;
          fi
          
          # Copy .dmg if it exists
          if [ -d "bundle/dmg" ]; then
            find bundle/dmg -name "*.dmg" -exec cp {} "$GITHUB_WORKSPACE/artifacts/" \;
          fi
          
      - name: Prepare artifacts (Windows)
        if: matrix.settings.runner == 'windows-latest'
        run: |
          mkdir artifacts
          cd target/${{ matrix.settings.target }}/release
          
          # Copy the CLI binary if it exists
          if (Test-Path "cap.exe") {
            Copy-Item "cap.exe" "$env:GITHUB_WORKSPACE/artifacts/cap-${{ matrix.settings.target }}.exe"
          }
          if (Test-Path "Cap.exe") {
            Copy-Item "Cap.exe" "$env:GITHUB_WORKSPACE/artifacts/cap-${{ matrix.settings.target }}.exe"
          }
          
          # Copy MSI installer if it exists
          if (Test-Path "bundle/msi") {
            Get-ChildItem "bundle/msi/*.msi" | ForEach-Object {
              Copy-Item $_.FullName "$env:GITHUB_WORKSPACE/artifacts/"
            }
          }
          
          # Copy NSIS installer if it exists
          if (Test-Path "bundle/nsis") {
            Get-ChildItem "bundle/nsis/*.exe" | ForEach-Object {
              Copy-Item $_.FullName "$env:GITHUB_WORKSPACE/artifacts/"
            }
          }
        shell: powershell
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cap-desktop-${{ matrix.settings.target }}
          path: artifacts/
          retention-days: 30
          
      - name: List prepared artifacts (debug)
        run: |
          echo "=== Artifacts prepared for ${{ matrix.settings.target }} ==="
          ls -la artifacts/ || echo "No artifacts directory"
        shell: bash

  create-release:
    needs: [get-version, build]
    runs-on: ubuntu-latest
    if: always() && needs.build.result == 'success'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Fetch upstream tags and checkout
        run: |
          git remote add upstream https://github.com/CapSoftware/Cap.git || true
          git fetch upstream --tags
          git checkout ${{ needs.get-version.outputs.tag }}
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          
      - name: List release artifacts (debug)
        run: |
          echo "=== All artifacts downloaded for release ==="
          find release-artifacts -type f -name "*" | head -20
          echo "=== Total file count ==="
          find release-artifacts -type f | wc -l
          echo "=== Files that will be uploaded ==="
          find release-artifacts -name "*.dmg" -o -name "*.app" -o -name "*.exe" -o -name "*.msi" -o -name "cap-*" -o -name "Cap-*" | head -20
        shell: bash
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-version.outputs.tag }}
          name: "Cap Desktop v${{ needs.get-version.outputs.version }} (Open Source Build)"
          draft: false
          prerelease: false
          body: |
            # Cap Desktop v${{ needs.get-version.outputs.version }}
            
            This is an **open source build** of Cap Desktop, built automatically from the [official source code](https://github.com/CapSoftware/Cap).
            
            ## Important Notes
            - 🔓 **No commercial license required** - this build is from source code
            - 🚫 **No proprietary features** - some cloud integrations may be disabled
            - ⚠️ **Community build** - not officially supported by Cap team
            - 🔄 **Auto-updated** - built automatically when new versions are released
            
            ## Downloads
            - **macOS Apple Silicon**: Download the `.app` or binary for M1/M2/M3 Macs
            - **macOS Intel**: Download the `.app` or binary for Intel Macs  
            - **Windows x64**: Download the `.exe` file
            
            ## Source
            Built from commit: ${{ github.sha }}
            Original release: https://github.com/CapSoftware/Cap/releases/tag/${{ needs.get-version.outputs.tag }}
          files: |
            release-artifacts/**/*.dmg
            release-artifacts/**/*.app
            release-artifacts/**/*.exe
            release-artifacts/**/*.msi
            release-artifacts/**/cap-*
            release-artifacts/**/Cap-*
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 